### ISSUE TITLE
 EISDIR: illegal operation on a directory, read

### ISSUE THREAD

**Issue by FlorianOrtner** [psauthor/MeterReader#24]
Hi,
building the client fails (branch .Net 8):

```
PS X:\git\#Plurasight\MeterReader\src\MeterReader\client> npm run build

> client@0.0.0 build
> vue-tsc --noEmit && vite build

vite v2.7.1 building for production...
✓ 0 modules transformed.
[vite:build-html] EISDIR: illegal operation on a directory, read
file: X:/git/#Plurasight/MeterReader/src/MeterReader/client/index.html
error during build:
Error: EISDIR: illegal operation on a directory, read
    at async readFileHandle (node:internal/fs/promises:554:24)
    at async fileToBuiltUrl (X:\git\#Plurasight\MeterReader\src\MeterReader\client\node_modules\vite\dist\node\chunks\dep-3daf770c.js:6030:21)
    at async Object.transform (X:\git\#Plurasight\MeterReader\src\MeterReader\client\node_modules\vite\dist\node\chunks\dep-3daf770c.js:21539:31)
    at async ModuleLoader.addModuleSource (X:\git\#Plurasight\MeterReader\src\MeterReader\client\node_modules\rollup\dist\shared\rollup.js:22161:30)```

**Comment by shawnwildermuth** [comment]
this looks like a permissions issue. Can you post a repro?
